### ISSUE TITLE
Disallowed Licences

### ISSUE THREAD

**Issue by tomgco** [behance/license-to-fail#12]
It would be nice to disallow a particular licence.

For example:

```json
"license-to-fail": {                                                                                                                  
  "disallowedLicenses": [                                                                                                                
    "GPL"                                                                                                                             
  ]                                                                                                                                   
}   
```

**Comment by hzoo** [comment]
Thanks for the suggestion - so far I think we decided to go with a whitelist rather than blacklist to be opt-in instead of opt-out

**Comment by tomgco** [comment]
> Thanks for the suggestion - so far I think we decided to go with a whitelist rather than blacklist to be opt-in instead of opt-out

Would you be open to a PR for the new feature?

**Comment by hzoo** [comment]
I'm hesitant to since my argument is that it's safer to have a list of licenses you approve and then you would just add more to the whitelist as you find ones that fail and you actually want?

Otherwise you would be allowing any licenses other than GPL and maybe there's a new one that's basically the same but called something else (not likely but just an example).

Or is that maintenance too annoying (I can see that)

**Comment by tomgco** [comment]
> I'm hesitant to since my argument is that it's safer to have a list of licenses you approve and then you would just add more to the whitelist as you find ones that fail and you actually want?
> 
> Otherwise you would be allowing any licenses other than GPL and maybe there's a new one that's basically the same but called something else (not likely but just an example).
> 
> Or is that maintenance too annoying (I can see that)

Thanks for your response, I understand your point of view. Thanks for the work you have done!
