### ISSUE TITLE
Feature request: config option to ignore devDependencies

### ISSUE THREAD

**Issue by palmerj3** [behance/license-to-fail#8]
Most often, license issues arise with code that is shipped to users.

With that in mind it makes sense to have an option to ignore devDependencies via config.

**Comment by hzoo** [comment]
Hey @palmerj3! Are y'all planning on using? Makes sense to me - do you want to make a pr as well?

**Comment by hzoo** [comment]
And so build tools don't come up as much for issues?

**Comment by palmerj3** [comment]
Hey! We are already using it :)

Sure I'll work on a PR.

**Comment by palmerj3** [comment]
@hzoo https://github.com/behance/license-to-fail/pull/9

**Comment by hzoo** [comment]
https://github.com/behance/license-to-fail/pull/9
